name: Java CI Pipeline
  
on:
  push:
    branches: [ "new" ]
  pull_request:
    branches: [ "new" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     jar-ready: ${{ steps.jar.outputs.ready }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'

  #     - name: Build Spring Boot jar
  #       run: mvn clean package -DskipTests

  #     - name: Set flag if jar exists
  #       id: jar
  #       run: |
  #         if [ -f target/fitness-server-0.0.1-SNAPSHOT.jar ]; then
  #           echo "ready=true" >> $GITHUB_OUTPUT
  #         else
  #           echo "ready=false" >> $GITHUB_OUTPUT
  #         fi

  # client_setup:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: client
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'

  #     - name: Set default NPM registry
  #       run: npm config set registry https://registry.npmjs.org/

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build client
  #       run: npm run build

  #     - name: Upload client artifacts (node_modules + dist)
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: client-artifact
  #         path: |
  #           client/node_modules
  #           client/dist
  #           client/.next  # включить, если используется Next.js

  # client_test:
  #   runs-on: ubuntu-latest
  #   needs: client_setup
  #   defaults:
  #     run:
  #       working-directory: client
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  
  #     - name: Install dependencies
  #       run: npm ci
  
  #     - name: Run client tests
  #       run: npm test -- --watchAll=false

  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build, client_test]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Compose
  #       run: |
  #         docker compose -f docker-compose.yml up -d
  #         docker ps

  #     - name: Wait for Kafka to become available
  #       run: |
  #         echo "Waiting for Kafka to be ready..."
  #         for i in {1..12}; do
  #           if docker exec fitnessserver-kafka-1-1 kafka-topics --bootstrap-server localhost:9092 --list; then
  #             echo "Kafka is ready!"
  #             break
  #           fi
  #           echo "Waiting for Kafka... Attempt $i"
  #           sleep 10
  #         done

  #     - name: Create Kafka topics
  #       run: |
  #         docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic heart-rate-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 || true
  #         docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic location-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 || true
  #         docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic steps-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 || true
  #         docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic battery-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 || true

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'

  #     - name: Build Spring Boot jar (again for context)
  #       run: mvn clean package -DskipTests

  #     - name: Run Spring Boot app in background
  #       run: java -jar target/fitness-server-*.jar &

  #     - name: Wait for Spring Boot app to become available
  #       run: |
  #         echo "Waiting for Spring Boot to be ready..."
  #         for i in {1..20}; do
  #           if curl -s http://localhost:8080/actuator/health | grep UP; then
  #             echo "Spring Boot is ready!"
  #             break
  #           fi
  #           echo "Waiting..."
  #           sleep 5
  #         done

  # docker_push:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: "alexsa7161"
  #         password: "dckr_pat_9Ufz_nFag9PwfoEzGozAR1NsNpc"
  
  #     - name: Build and push Docker image
  #       run: |
  #         docker build -t alexsa7161/fitness-backend_from_ci:latest .
  #         docker push alexsa7161/fitness-backend_from_ci:latest

  sonar_scan:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubeconfig and test connection
        run: |
          echo "Step 1: Create .kube directory"
          mkdir -p $HOME/.kube
      
          echo "Step 2: Decode kubeconfig from secret"
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
          echo "Step 3: Show first 20 lines of kubeconfig for debug"
          head -n 20 $HOME/.kube/config
      
          echo "Step 4: List contexts"
          kubectl config get-contexts
      
          echo "Step 5: Show current context"
          kubectl config current-context || echo "NO CURRENT CONTEXT"
      
          echo "Step 6: Set current context to github-actions"
          kubectl config use-context github-actions
      
          echo "Step 7: Verify connection by listing nodes"
          kubectl get nodes


  
      - name: Delete old SonarQube job (ignore if not exists)
        run: |
          kubectl delete job sonar-scan -n fitness-app || echo "Job not found"
  
      - name: Apply SonarQube job
        run: kubectl apply -f ./sonar-job.yaml

      - name: Wait for SonarQube job to finish
        run: |
          JOB_NAME=sonar-scan
          NAMESPACE=fitness-app
          kubectl wait --for=condition=complete --timeout=600s job/$JOB_NAME -n $NAMESPACE
          echo "SonarQube job completed"
  
      - name: Check Sonar Quality Gate and Coverage
        run: |
          SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" # например https://sonar.example.com
          SONAR_PROJECT_KEY="fitness-app"
          SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}"
  
          RESPONSE=$(curl -s -u "$SONAR_TOKEN:" "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$SONAR_PROJECT_KEY")

          STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status')
          COVERAGE=$(echo "$RESPONSE" | jq -r '.projectStatus.conditions[] | select(.metricKey=="coverage") | .actualValue')

          echo "Quality Gate Status: $STATUS"
          echo "Coverage: $COVERAGE%"

          if [ "$STATUS" != "OK" ]; then
            echo "❌ SonarQube Quality Gate failed"
            exit 1
          fi

          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "❌ Code coverage is below 80%"
            exit 1
          fi

          echo "✅ SonarQube Quality Gate passed and coverage is OK"



  # cleanup:
  #   runs-on: ubuntu-latest
  #   needs: [test, sonar_scan]
  #   if: always()
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Tear down Docker containers
  #       run: docker compose -f docker-compose.yml down
