name: Java CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          docker ps

      - name: Wait for Kafka to become available
        run: |
          echo "Waiting for Kafka to be ready..."
          sleep 30  # Простая задержка (можно заменить на healthcheck + curl + netcat и т.д.)

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot jar
        run: mvn clean package -DskipTests

      - name: Run Spring Boot app in background
        run: java -jar target/fitness-server-*.jar &

      - name: Wait for Spring Boot app to become available
        run: |
          echo "Waiting for Spring Boot to be ready..."
          for i in {1..20}; do
            curl -s http://localhost:8080/actuator/health && break
            echo "Waiting..."
            sleep 5
          done

      - name: Run Maven tests
        run: mvn test

      - name: Tear down Docker containers
        if: always()
        run: docker-compose -f docker-compose.yml down
