name: Java CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose (Kafka, Flink)
        run: |
          docker compose -f docker-compose.yml up -d
          docker ps

      - name: Wait for Kafka to become available
        run: |
          echo "Waiting for Kafka to be ready..."
          sleep 30

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permissions for Maven wrapper
        run: chmod +x mvnw

      - name: Build project (without tests)
        run: ./mvnw clean install -DskipTests

      - name: Start Spring Boot app in background
        run: |
          echo "Starting Spring Boot app..."
          nohup ./mvnw spring-boot:run > app.log 2>&1 &

      - name: Wait for Spring Boot app to become available
        run: |
          echo "Waiting for Spring Boot to be ready..."
          for i in {1..20}; do
            curl -s http://localhost:8080/actuator/health && break
            echo "Waiting..."
            sleep 5
          done

      - name: Run tests
        run: ./mvnw test

      - name: Print Spring logs on failure (optional)
        if: failure()
        run: cat app.log

      - name: Tear down Docker containers
        if: always()
        run: docker compose -f docker-compose.yml down

