name: Java CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar-ready: ${{ steps.jar.outputs.ready }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot jar
        run: mvn clean package -DskipTests

      - name: Set flag if jar exists
        id: jar
        run: |
          if [ -f target/fitness-server-0.0.1-SNAPSHOT.jar ]; then
            echo "ready=true" >> $GITHUB_OUTPUT
          else
            echo "ready=false" >> $GITHUB_OUTPUT
          fi

  client_prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set default NPM registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build client
        run: npm run build

  client_test:
    runs-on: ubuntu-latest
    needs: client_prepare
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run client tests
        run: npm test -- --watchAll=false

  server:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          docker ps

      - name: Wait for Kafka to become available
        run: |
          echo "Waiting for Kafka to be ready..."
          for i in {1..10}; do
            if docker exec fitnessserver-kafka-1-1 kafka-topics --bootstrap-server kafka1:29092 --list; then
              echo "Kafka is ready!"
              break
            fi
            echo "Waiting for Kafka to be ready... Attempt $i"
            sleep 10
          done

      - name: Create Kafka topics
        run: |
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic heart-rate-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic location-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic steps-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic battery-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1

      - name: Verify topics were created
        run: |
          docker exec fitnessserver-kafka-1-1 kafka-topics --bootstrap-server kafka1:29092 --list

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot jar (again for context)
        run: mvn clean package -DskipTests

      - name: Run Spring Boot app in background
        run: java -jar target/fitness-server-*.jar &

      - name: Wait for Spring Boot app to become available
        run: |
          echo "Waiting for Spring Boot to be ready..."
          for i in {1..20}; do
            curl -s http://localhost:8080/actuator/health && break
            echo "Waiting..."
            sleep 5
          done

  server_test:
    runs-on: ubuntu-latest
    needs: server  # зависит от шага, где поднят Docker Compose
    steps:
      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          docker ps

      - name: Wait for Kafka to become available
        run: |
          echo "Waiting for Kafka to be ready..."
          for i in {1..10}; do
            if docker exec fitnessserver-kafka-1-1 kafka-topics --bootstrap-server kafka1:29092 --list; then
              echo "Kafka is ready!"
              break
            fi
            echo "Waiting for Kafka to be ready... Attempt $i"
            sleep 10
          done

      - name: Create Kafka topics
        run: |
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic heart-rate-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic location-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic steps-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1
          docker exec fitnessserver-kafka-1-1 kafka-topics --create --topic battery-topic --bootstrap-server kafka1:29092 --replication-factor 3 --partitions 1
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          mvn test \
            -Dspring.datasource.url=jdbc:postgresql://localhost:5432/fitnessdb \
            -Dspring.datasource.username=postgres \
            -Dspring.datasource.password=postgres

  cleanup:
    runs-on: ubuntu-latest
    needs: [client_test, server_test]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tear down Docker containers
        run: docker compose -f docker-compose.yml down
